services:
  redis-preprod-dev:
    image: redis:7-alpine
    command: redis-server --requirepass "Tex@2025dev"
    ports:
      - "6391:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Tex@2025dev", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
