services:
  redis-prod:
    image: redis:7.2
    container_name: redis-prod
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/prod:/data
    restart: always

  redis-dev:
    image: redis:7.2
    container_name: redis-dev
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - ./data/dev:/data
    restart: always

  redis-local:
    image: redis:7.2
    container_name: redis-local
    command: redis-server --appendonly yes
    ports:
      - "6381:6379"
    volumes:
      - ./data/local:/data
    restart: unless-stopped
